pipeline:
  build:
    image: java:8u91-jdk
    commands:
      - ./gradlew build --stacktrace
    when:
      branches: [ master, development, pull/* ]
      event: [ tag, push ]

  publish:
    image: plugins/docker
    repo: eltesoftwaretechnology/admin-backend
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    auto_tag: true

  rancher:
    image: peloton/drone-rancher
    url: http://178.62.230.163:8080
    secrets: [ rancher_access_key, rancher_secret_key ]
    service: adminbe/api
    docker_image: "eltesoftwaretechnology/admin-backend:${DRONE_TAG##v}"
    start_first: false
    confirm: false
    timeout: 180
    when:
      branches: master
      event: tag

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: admin-be-technical
    username: Drone
    icon_url: https://lionell.me/img/Logo%20-%20Drone.png
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        Build {{build.number}} succeeded. Good job {{build.author}}! :)
      {{else}}
        Build {{build.number}} failed. :( {{build.author}}, you can see what went wrong here: {{build.link}}
      {{/success}}